apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: pod-reader
    namespace: development
  rules:
  - apiGroups:
    - '*'
    resources: ["deployments", "pods", "pods/log", "services"]
    verbs: ["get", "list", "watch"]
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
