apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
          #creationTimestamp: "2022-04-08T21:41:54Z"
    name: developement-binding
    namespace: development
    #resourceVersion: "1516"
    #uid: a62aaeca-6a8d-42d9-8c6d-089f15e51b18
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pod-reader
  subjects:
          #- apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: dev-sa
    namespace: development
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
